#!/usr/bin/env python3
"""Generate a PyInstaller ``--version-file`` for the Windows frozen runtime.

An unsigned PyInstaller .exe with *no* version-info resource looks more
suspicious to antivirus heuristics (and to users inspecting Properties). Stamping
CompanyName / ProductName / FileVersion is a free, signing-independent way to
reduce false positives and make the binary look like what it is. See
``docs/windows-antivirus.md``.

Usage:
    python scripts/gen_win_version_info.py --kernel-version 0.16.0 \
        --runtime-version 0.16.0-cn.1 --output version_info.txt

The output is a Python file in PyInstaller's VSVersionInfo text format; pass it
to ``pyinstaller --version-file``. Use ``--check`` on an existing file to verify
it is syntactically valid Python (the only thing reproducible off-Windows).
"""

from __future__ import annotations

import argparse
import re
import sys

_TEMPLATE = """\
# UTF-8
# PyInstaller version-info resource for the Hermes Agent CN Windows runtime.
# Generated by scripts/gen_win_version_info.py — do not edit by hand.
VSVersionInfo(
    ffi=FixedFileInfo(
        filevers={vers},
        prodvers={vers},
        mask=0x3F,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    "040904B0",
                    [
                        StringStruct("CompanyName", "Hermes Agent CN"),
                        StringStruct("FileDescription", "Hermes Agent CN Runtime"),
                        StringStruct("FileVersion", "{runtime_version}"),
                        StringStruct("InternalName", "hermes-agent-cn-runtime"),
                        StringStruct(
                            "LegalCopyright",
                            "Hermes Agent CN community. Apache-2.0.",
                        ),
                        StringStruct(
                            "OriginalFilename", "hermes-agent-cn-runtime.exe"
                        ),
                        StringStruct("ProductName", "Hermes Agent CN Runtime"),
                        StringStruct("ProductVersion", "{runtime_version}"),
                    ],
                )
            ]
        ),
        VarFileInfo([VarStruct("Translation", [0x409, 1200])]),
    ],
)
"""


def _vers_tuple(kernel_version: str) -> tuple[int, int, int, int]:
    parts = re.findall(r"\d+", kernel_version)
    nums = [int(p) for p in parts[:3]]
    while len(nums) < 4:
        nums.append(0)
    return tuple(nums[:4])  # type: ignore[return-value]


def render(kernel_version: str, runtime_version: str) -> str:
    return _TEMPLATE.format(
        vers=_vers_tuple(kernel_version),
        runtime_version=runtime_version,
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kernel-version", default="0.0.0")
    parser.add_argument("--runtime-version", default="0.0.0")
    parser.add_argument("--output", default="version_info.txt")
    parser.add_argument(
        "--check",
        metavar="FILE",
        help="Verify FILE compiles as valid Python and exit.",
    )
    args = parser.parse_args(argv)

    if args.check:
        with open(args.check, encoding="utf-8") as fh:
            source = fh.read()
        compile(source, args.check, "exec")  # raises SyntaxError if malformed
        print(f"{args.check}: OK")
        return 0

    text = render(args.kernel_version, args.runtime_version)
    # Fail loudly here rather than at PyInstaller time if the template ever drifts.
    compile(text, args.output, "exec")
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {args.output} (filevers={_vers_tuple(args.kernel_version)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
